// All-Clear Scenario - Normal driving conditions
// Baseline scenario with no weather hazards
export default {
  id: 'all-clear',
  name: 'All Clear - Normal Conditions',
  description: 'Clear weather conditions along I-65 Nashville to Louisville. Demonstrates baseline monitoring behavior.',
  hazardType: 'NONE',
  region: 'I-65 Corridor, KY/TN',
  center: { lat: 37.00, lon: -86.00 },
  route: {
    from: { lat: 36.16, lon: -86.78, label: 'Nashville, TN' },
    to: { lat: 38.25, lon: -85.76, label: 'Louisville, KY' },
  },
  timeline: [
    {
      minutesMark: 0,
      riskScore: 0.05,
      tier: 'MONITORING',
      alertMessage: 'Trip started. Clear skies and dry conditions along I-65 north.',
      recommendedAction: 'CONTINUE_MONITORING',
      stormCells: [],
      shelters: [],
    },
    {
      minutesMark: 10,
      riskScore: 0.05,
      tier: 'MONITORING',
      alertMessage: 'Conditions remain clear. No weather hazards detected within 50-mile radius.',
      recommendedAction: 'CONTINUE_MONITORING',
      stormCells: [],
      shelters: [],
    },
    {
      minutesMark: 20,
      riskScore: 0.08,
      tier: 'MONITORING',
      alertMessage: 'Passing Bowling Green, KY. Fair weather cumulus clouds. No severe weather outlook for next 6 hours.',
      recommendedAction: 'CONTINUE_MONITORING',
      stormCells: [],
      shelters: [],
    },
    {
      minutesMark: 30,
      riskScore: 0.05,
      tier: 'MONITORING',
      alertMessage: 'Approaching Elizabethtown, KY. All clear — no watches, warnings, or advisories in effect.',
      recommendedAction: 'CONTINUE_MONITORING',
      stormCells: [],
      shelters: [],
    },
    {
      minutesMark: 40,
      riskScore: 0.03,
      tier: 'MONITORING',
      alertMessage: 'Arriving Louisville metro area. Trip completed safely under clear conditions.',
      recommendedAction: 'CONTINUE_MONITORING',
      stormCells: [],
      shelters: [],
    },
  ],
};
