spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  graphql:
    graphiql:
      enabled: false

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.weatherwise: INFO
    org.hibernate.SQL: WARN
