server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/weatherwise}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /subscriptions

nws:
  api:
    base-url: https://api.weather.gov
    user-agent: "WeatherWise/1.0 (contact@weatherwise.dev)"

ml:
  service:
    url: http://localhost:5000

osrm:
  api:
    url: http://router.project-osrm.org
